apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: e2e-fbc-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/e2e-fbc-application/e2e-fbc-component@sha256:d24484892eb8f8cdd3a0c5fcded6c9a09641035be8b7b3c24305472e32dd441c
        name: fbc
        resources: {}
status: {}
